name: Generate Snake Animation

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake GIF and SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: edwin-biju
          outputs: |
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Generated Snake Animation 🐍"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
